### ISSUE TITLE
您好，能不能重新编译一下库，打印日志太频繁。

### ISSUE THREAD

**Issue by ydajiang** [Mr-Jiang/G711A#1]

**Comment by Mr-Jiang** [comment]
你关注一下我，等我更新了你能第一时间收到通知，我把对应的NDK打印全部给你去掉

**Comment by Mr-Jiang** [comment]
https://github.com/Mr-Jiang/G711A/commit/4161ba13b1eac9fd410045499a09a67b106e9806
